### ISSUE TITLE
Pull stuff in from upstream?

### ISSUE THREAD

**Issue by jstorimer** [Sirupsen/syck#2]
I noticed that tenderlove/syck has some new commits that aren't in this fork. Most of it is irrelevant dev stuff, but this commit is one we might need? https://github.com/tenderlove/syck/commit/1f148c39cf9f538c0b2a54ef0289b65894973600

@Sirupsen or @csfrancis will know for sure.

**Comment by jstorimer** [comment]
Link to upstream: https://github.com/tenderlove/syck/commits/master

**Comment by sirupsen** [comment]
@csfrancis already made [a PR](https://github.com/Sirupsen/syck/pull/1). There's more to be done though, because switching between engines was removed in 2.2.0's version of Psych AFAIK. We're holding off upgrading to Ruby 2.2.0 until Rails 4.2 ships @csfrancis mentioned, because there are some regressions etc., that were fixed upstream in Rails 4.2.

**Comment by jstorimer** [comment]
:+1:
